CipherPhole/diffmodel-manga-image-translator

manga_translator/translators/groq.py

for testing deepseek

---

manga_translator/translators/groq.py

change temp and top_p to 0

---

manga_translator/translators/groq.py

Temperature = 0.2 and Top_p = 0.9

Temperature = 0.2 and Top_p = 0.9

---

manga_translator/translators/groq.py

Refine Chat Template

---

manga_translator/translators/groq.py

Reverts CipherPhole/diffmodel-manga-image-translator#4

Revert "Refine Chat Template"

---

manga_translator/translators/groq.py

revert and refined further

---

manga_translator/translators/groq.py

Tweaks Inference Chat Template

Tweaks Inference Chat Template

---

manga_translator/translators/groq.py

Tweaks Inference Chat Template 2

Tweaks Inference Chat Template 2

---

requirements.txt

fix paddle req text

---

requirements.txt

Update requirements.txt openai error web fix

Update requirements.txt openai error web fix

---

manga_translator/detection/default.py

newdetectmodel-1

---

manga_translator/translators/groq.py

textlengthcontrol

---

manga_translator/translators/groq.py

Reverts CipherPhole/diffmodel-manga-image-translator#16

Revert "textlengthcontrol"

---

manga_translator/translators/groq.py

Update groq.py textlenghtcontrol2

Update groq.py textlenghtcontrol2

---

manga_translator/translators/groq.py

Update groq.py textlenghtcontrol3

Update groq.py textlenghtcontrol3

---

manga_translator/translators/groq.py

heavy update to groq.py

---

manga_translator/translators/groq.py

Update groq.py to deepqwen32b model

Update groq.py to deepqwen32b model

---

manga_translator/translators/groq.py

Reverts CipherPhole/diffmodel-manga-image-translator#21

Revert "Update groq.py to deepqwen32b model"

---

manga_translator/translators/groq.py

Update groq.py controlled genders

Update groq.py controlled genders

---

manga_translator/translators/groq.py

Update groq.py used double quotes fix errror

Update groq.py used double quotes fix errror

---

manga_translator/translators/groq.py

Update groq.py fix san

---

manga_translator/translators/groq.py

Update groq.py to refinesan

---

manga_translator/translators/groq.py

Update groq.py to reinforcesanfirst

Update groq.py to reinforcesanfirst

---

manga_translator/translators/groq.py

Reverts CipherPhole/diffmodel-manga-image-translator#35

Revert "Update groq.py"

---

manga_translator/translators/groq.py

Reverts CipherPhole/diffmodel-manga-image-translator#54

Revert "Revert "Update groq.py""

---

manga_translator/translators/groq.py

Reverts CipherPhole/diffmodel-manga-image-translator#60

Revert "fix for /n and backlashes"

---

manga_translator/translators/groq.py

Reverts CipherPhole/diffmodel-manga-image-translator#81

Revert "Update groq.py fixpropernounusage"

---

manga_translator/translators/groq.py

Reverts CipherPhole/diffmodel-manga-image-translator#83

Revert "Update groq.py educeby-.5topp"
